name: Release assets

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build release assets
        run: make release

      - name: Upload release assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./docker-gen-*.tar.gz"]'

      - name: Cleanup release assets
        run: make dist-clean
